/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator.swing;

import java.awt.Color;
import java.awt.Graphics;
import java.text.DecimalFormat;
import javax.swing.BorderFactory;
import javax.swing.JFrame;

/**
 *
 * @author Connor
 */
public class Calculator extends javax.swing.JPanel {
    
    boolean light = true;
    Color panelBackground = new Color(236,236,236);
    Color buttonBackground = new Color(184,178,158);
    Color operatorLight = new Color(99,92,74);
    Color operatorDark = new Color(77,76,76);
    double num, ans;
    int calculation;
    DecimalFormat df = new DecimalFormat("######.####");
    
    
    
    
    /**
     * Creates new form NewJPanel
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        text = new javax.swing.JTextField();
        cache = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bequal = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        bdiv = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        bmult = new javax.swing.JButton();
        bminus = new javax.swing.JButton();
        badd = new javax.swing.JButton();
        breset = new javax.swing.JButton();
        bd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(32, 32, 32));
        setForeground(new java.awt.Color(32, 32, 32));

        jPanel1.setBackground(new java.awt.Color(216, 219, 212));

        text.setBackground(new java.awt.Color(186, 180, 160));
        text.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        text.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        cache.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cache.setForeground(new java.awt.Color(255, 101, 56));
        cache.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 2, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 101, 56));
        jLabel2.setText("I <3 Java");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(text)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cache, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cache, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 101, 56));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );

        bequal.setBackground(jPanel2.getBackground());
        bequal.setFont(new java.awt.Font("Rockwell Condensed", 1, 48)); // NOI18N
        bequal.setForeground(new java.awt.Color(255, 255, 255));
        bequal.setText("=");
        bequal.setBorderPainted(false);
        bequal.setContentAreaFilled(false);
        bequal.setFocusPainted(false);
        bequal.setFocusable(false);
        bequal.setMargin(new java.awt.Insets(2, 220, 2, 14));
        bequal.setOpaque(true);
        bequal.setRequestFocusEnabled(false);
        bequal.setRolloverEnabled(false);
        bequal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bequalMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bequalMouseReleased(evt);
            }
        });

        b7.setBackground(new java.awt.Color(42, 42, 42));
        b7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b7.setForeground(new java.awt.Color(98, 91, 73));
        b7.setText("7");
        b7.setBorderPainted(false);
        b7.setContentAreaFilled(false);
        b7.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        b7.setFocusPainted(false);
        b7.setFocusable(false);
        b7.setOpaque(true);
        b7.setRequestFocusEnabled(false);
        b7.setRolloverEnabled(false);
        b7.setVerifyInputWhenFocusTarget(false);
        b7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b7MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                b7MouseReleased(evt);
            }
        });

        bdiv.setBackground(new java.awt.Color(77, 76, 76));
        bdiv.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bdiv.setForeground(new java.awt.Color(255, 255, 255));
        bdiv.setText("/");
        bdiv.setBorderPainted(false);
        bdiv.setContentAreaFilled(false);
        bdiv.setFocusPainted(false);
        bdiv.setFocusable(false);
        bdiv.setOpaque(true);
        bdiv.setRequestFocusEnabled(false);
        bdiv.setRolloverEnabled(false);
        bdiv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bdivMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bdivMouseReleased(evt);
            }
        });

        b8.setBackground(new java.awt.Color(42, 42, 42));
        b8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b8.setForeground(new java.awt.Color(98, 91, 73));
        b8.setText("8");
        b8.setBorderPainted(false);
        b8.setContentAreaFilled(false);
        b8.setFocusPainted(false);
        b8.setFocusable(false);
        b8.setOpaque(true);
        b8.setVerifyInputWhenFocusTarget(false);
        b8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b8MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                b8MouseReleased(evt);
            }
        });

        b9.setBackground(new java.awt.Color(42, 42, 42));
        b9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b9.setForeground(new java.awt.Color(98, 91, 73));
        b9.setText("9");
        b9.setBorder(null);
        b9.setBorderPainted(false);
        b9.setContentAreaFilled(false);
        b9.setFocusPainted(false);
        b9.setFocusable(false);
        b9.setOpaque(true);
        b9.setRequestFocusEnabled(false);
        b9.setRolloverEnabled(false);
        b9.setVerifyInputWhenFocusTarget(false);
        b9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b9MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                b9MouseReleased(evt);
            }
        });

        b4.setBackground(new java.awt.Color(42, 42, 42));
        b4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b4.setForeground(new java.awt.Color(98, 91, 73));
        b4.setText("4");
        b4.setBorderPainted(false);
        b4.setContentAreaFilled(false);
        b4.setFocusPainted(false);
        b4.setFocusable(false);
        b4.setOpaque(true);
        b4.setRequestFocusEnabled(false);
        b4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                b4MouseReleased(evt);
            }
        });

        b5.setBackground(new java.awt.Color(42, 42, 42));
        b5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b5.setForeground(new java.awt.Color(98, 91, 73));
        b5.setText("5");
        b5.setBorderPainted(false);
        b5.setContentAreaFilled(false);
        b5.setDefaultCapable(false);
        b5.setFocusPainted(false);
        b5.setFocusable(false);
        b5.setOpaque(true);
        b5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                b5MouseReleased(evt);
            }
        });

        b6.setBackground(new java.awt.Color(42, 42, 42));
        b6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b6.setForeground(new java.awt.Color(98, 91, 73));
        b6.setText("6");
        b6.setBorderPainted(false);
        b6.setContentAreaFilled(false);
        b6.setFocusable(false);
        b6.setOpaque(true);
        b6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                b6MouseReleased(evt);
            }
        });

        b1.setBackground(new java.awt.Color(42, 42, 42));
        b1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b1.setForeground(new java.awt.Color(98, 91, 73));
        b1.setText("1");
        b1.setBorderPainted(false);
        b1.setContentAreaFilled(false);
        b1.setFocusPainted(false);
        b1.setFocusable(false);
        b1.setOpaque(true);
        b1.setRequestFocusEnabled(false);
        b1.setRolloverEnabled(false);
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                b1MouseReleased(evt);
            }
        });

        b3.setBackground(new java.awt.Color(42, 42, 42));
        b3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b3.setForeground(new java.awt.Color(98, 91, 73));
        b3.setText("3");
        b3.setBorderPainted(false);
        b3.setContentAreaFilled(false);
        b3.setFocusPainted(false);
        b3.setFocusable(false);
        b3.setOpaque(true);
        b3.setRequestFocusEnabled(false);
        b3.setRolloverEnabled(false);
        b3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                b3MouseReleased(evt);
            }
        });

        b0.setBackground(new java.awt.Color(42, 42, 42));
        b0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b0.setForeground(new java.awt.Color(98, 91, 73));
        b0.setText("0");
        b0.setBorderPainted(false);
        b0.setContentAreaFilled(false);
        b0.setFocusPainted(false);
        b0.setFocusable(false);
        b0.setOpaque(true);
        b0.setRequestFocusEnabled(false);
        b0.setRolloverEnabled(false);
        b0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b0MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                b0MouseReleased(evt);
            }
        });

        b2.setBackground(new java.awt.Color(42, 42, 42));
        b2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b2.setForeground(new java.awt.Color(98, 91, 73));
        b2.setText("2");
        b2.setBorderPainted(false);
        b2.setContentAreaFilled(false);
        b2.setFocusPainted(false);
        b2.setOpaque(true);
        b2.setRequestFocusEnabled(false);
        b2.setRolloverEnabled(false);
        b2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                b2MouseReleased(evt);
            }
        });

        bmult.setBackground(new java.awt.Color(77, 76, 76));
        bmult.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bmult.setForeground(new java.awt.Color(255, 255, 255));
        bmult.setText("*");
        bmult.setBorderPainted(false);
        bmult.setContentAreaFilled(false);
        bmult.setFocusPainted(false);
        bmult.setFocusable(false);
        bmult.setOpaque(true);
        bmult.setRequestFocusEnabled(false);
        bmult.setRolloverEnabled(false);
        bmult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bmultMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bmultMouseReleased(evt);
            }
        });

        bminus.setBackground(new java.awt.Color(77, 76, 76));
        bminus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bminus.setForeground(new java.awt.Color(255, 255, 255));
        bminus.setText("-");
        bminus.setBorderPainted(false);
        bminus.setContentAreaFilled(false);
        bminus.setFocusPainted(false);
        bminus.setFocusable(false);
        bminus.setOpaque(true);
        bminus.setRequestFocusEnabled(false);
        bminus.setRolloverEnabled(false);
        bminus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bminusMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bminusMouseReleased(evt);
            }
        });

        badd.setBackground(new java.awt.Color(77, 76, 76));
        badd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        badd.setForeground(new java.awt.Color(255, 255, 255));
        badd.setText("+");
        badd.setBorderPainted(false);
        badd.setContentAreaFilled(false);
        badd.setFocusPainted(false);
        badd.setFocusable(false);
        badd.setOpaque(true);
        badd.setRequestFocusEnabled(false);
        badd.setRolloverEnabled(false);
        badd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                baddMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                baddMouseReleased(evt);
            }
        });

        breset.setBackground(new java.awt.Color(77, 76, 76));
        breset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        breset.setForeground(new java.awt.Color(255, 255, 255));
        breset.setText("C");
        breset.setBorderPainted(false);
        breset.setContentAreaFilled(false);
        breset.setFocusPainted(false);
        breset.setFocusable(false);
        breset.setOpaque(true);
        breset.setRequestFocusEnabled(false);
        breset.setRolloverEnabled(false);
        breset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bresetMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bresetMouseReleased(evt);
            }
        });

        bd.setBackground(new java.awt.Color(77, 76, 76));
        bd.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bd.setForeground(new java.awt.Color(255, 255, 255));
        bd.setText(".");
        bd.setBorderPainted(false);
        bd.setContentAreaFilled(false);
        bd.setFocusPainted(false);
        bd.setFocusable(false);
        bd.setMargin(new java.awt.Insets(2, 14, 14, 14));
        bd.setOpaque(true);
        bd.setRequestFocusEnabled(false);
        bd.setRolloverEnabled(false);
        bd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bdMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bdMouseReleased(evt);
            }
        });
        bd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator/swing/CBH_toggleOrange.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bequal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(b2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bd, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(breset, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bminus, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(badd, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bmult, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bmult, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bminus, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(badd, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(breset, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bd, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bequal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b7MousePressed
        b7.setBackground(b8.getBackground().brighter());
        text.setText(text.getText() + "7");
    }//GEN-LAST:event_b7MousePressed

    private void b7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b7MouseReleased
        b7.setBackground(b8.getBackground());
    }//GEN-LAST:event_b7MouseReleased

    private void b8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b8MousePressed
         b8.setBackground(b8.getBackground().brighter());
        text.setText(text.getText() + "8");
    }//GEN-LAST:event_b8MousePressed

    private void b8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b8MouseReleased
        b8.setBackground(b7.getBackground());
    }//GEN-LAST:event_b8MouseReleased

    private void b9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b9MousePressed
        b9.setBackground(b8.getBackground().brighter());
        text.setText(text.getText() + "9");
    }//GEN-LAST:event_b9MousePressed

    private void b9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b9MouseReleased
        b9.setBackground(b8.getBackground());
    }//GEN-LAST:event_b9MouseReleased

    private void bdivMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bdivMousePressed
        bdiv.setBackground(badd.getBackground());
        num = Double.parseDouble(text.getText());
        calculation = 4;
        text.setText("");
        cache.setText(num + "/");
    }//GEN-LAST:event_bdivMousePressed

    private void bdivMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bdivMouseReleased
         bdiv.setBackground(badd.getBackground());
    }//GEN-LAST:event_bdivMouseReleased

    private void bmultMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmultMousePressed
       num = Double.parseDouble(text.getText());
        calculation = 3;
        text.setText("");
        cache.setText(num + "*");
    }//GEN-LAST:event_bmultMousePressed

    private void bmultMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmultMouseReleased
         bmult.setBackground(badd.getBackground());
    }//GEN-LAST:event_bmultMouseReleased

    private void baddMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baddMousePressed
         num = Double.parseDouble(text.getText());
        calculation = 1;
        text.setText("");
        cache.setText(num + "+");
    }//GEN-LAST:event_baddMousePressed

    private void baddMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baddMouseReleased
         badd.setBackground(bminus.getBackground());

    }//GEN-LAST:event_baddMouseReleased

    private void bdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bdMousePressed
        if(ans%1 == 0){
        bd.setBackground(badd.getBackground().brighter());
        text.setText(text.getText() + ".");
        }
        else{}
        
    }//GEN-LAST:event_bdMousePressed

    private void bdMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bdMouseReleased
         bd.setBackground(bminus.getBackground());
    }//GEN-LAST:event_bdMouseReleased

    private void bequalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bequalMousePressed
        bequal.setBackground(jPanel2.getBackground().brighter());
        arithmetic_operation();
        
        cache.setText("");
        
    }//GEN-LAST:event_bequalMousePressed

    private void bequalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bequalMouseReleased
        bequal.setBackground(jPanel2.getBackground());
        
    }//GEN-LAST:event_bequalMouseReleased

    private void b0MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b0MousePressed
         b0.setBackground(b8.getBackground().brighter());
        text.setText(text.getText() + "0");
    }//GEN-LAST:event_b0MousePressed

    private void b0MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b0MouseReleased
        b0.setBackground(b7.getBackground());
    }//GEN-LAST:event_b0MouseReleased

    private void bminusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bminusMousePressed
        bminus.setBackground(badd.getBackground().brighter());
        num = Double.parseDouble(text.getText());
        calculation = 2;
        text.setText("");
        cache.setText(num + "-");
    }//GEN-LAST:event_bminusMousePressed

    private void bminusMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bminusMouseReleased
        bminus.setBackground(badd.getBackground());
    }//GEN-LAST:event_bminusMouseReleased

    private void bresetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bresetMousePressed
       breset.setBackground(badd.getBackground().brighter());
        text.setText("");
        cache.setText("");
        ans = 0;
    }//GEN-LAST:event_bresetMousePressed

    private void bresetMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bresetMouseReleased
        breset.setBackground(badd.getBackground());
    }//GEN-LAST:event_bresetMouseReleased

    private void b4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MouseReleased
         b4.setBackground(b7.getBackground());
    }//GEN-LAST:event_b4MouseReleased

    private void b4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MousePressed
         b4.setBackground(b8.getBackground().brighter());
        text.setText(text.getText() + "4");
    }//GEN-LAST:event_b4MousePressed

    private void b3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MouseReleased
        b3.setBackground(b7.getBackground());
    }//GEN-LAST:event_b3MouseReleased

    private void b3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MousePressed
         b3.setBackground(b8.getBackground().brighter());
        text.setText(text.getText() + "3");
    }//GEN-LAST:event_b3MousePressed

    private void b2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MousePressed
        b2.setBackground(b8.getBackground().brighter());
        text.setText(text.getText() + "2");
    }//GEN-LAST:event_b2MousePressed

    private void b2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseReleased
        b2.setBackground(b7.getBackground());
    }//GEN-LAST:event_b2MouseReleased

    private void b1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MousePressed
        b1.setBackground(b5.getBackground().brighter());
        text.setText(text.getText() + "1");
    }//GEN-LAST:event_b1MousePressed

    private void b1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseReleased
        b1.setBackground(b7.getBackground());
    }//GEN-LAST:event_b1MouseReleased

    private void b6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b6MouseReleased
       b6.setBackground(b7.getBackground());
    }//GEN-LAST:event_b6MouseReleased

    private void b6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b6MousePressed
        b6.setBackground(b8.getBackground().brighter());
        text.setText(text.getText() + "6");
    }//GEN-LAST:event_b6MousePressed

    private void b5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5MouseReleased
       b5.setBackground(b7.getBackground());
    }//GEN-LAST:event_b5MouseReleased

    private void b5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5MousePressed
         b5.setBackground(b8.getBackground().brighter());
        text.setText(text.getText() + "5");
    }//GEN-LAST:event_b5MousePressed

    private void bdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bdActionPerformed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        if(!light){
           jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator/swing/CBH_toggleOrange.png")));
           b0.setBackground(new Color(42,42,42));
           b1.setBackground(new Color(42,42,42));
           b2.setBackground(new Color(42,42,42));
           b3.setBackground(new Color(42,42,42));
           b4.setBackground(new Color(42,42,42));
           b5.setBackground(new Color(42,42,42));
           b6.setBackground(new Color(42,42,42));
           b7.setBackground(new Color(42,42,42));
           b8.setBackground(new Color(42,42,42));
           b9.setBackground(new Color(42,42,42));
           bd.setBackground(operatorDark);
            badd.setBackground(operatorDark);
            bdiv.setBackground(operatorDark);
            bmult.setBackground(operatorDark);
            bminus.setBackground(operatorDark);
            breset.setBackground(operatorDark);
           setBackground(new Color(32,32,32));
           light = true;
        }
        else if(light) {            
        b0.setBackground(buttonBackground);
        b1.setBackground(buttonBackground);
        b2.setBackground(buttonBackground);
        b3.setBackground(buttonBackground);
        b4.setBackground(buttonBackground);
        b5.setBackground(buttonBackground);
        b6.setBackground(buttonBackground);
        b7.setBackground(buttonBackground);
        b8.setBackground(buttonBackground);
        b9.setBackground(buttonBackground);
        bd.setBackground(operatorLight);
        badd.setBackground(operatorLight);
        bdiv.setBackground(operatorLight);
        bmult.setBackground(operatorLight);
        bminus.setBackground(operatorLight);
        breset.setBackground(operatorLight);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator/swing/toggleBlack.png")));     
        setBackground(panelBackground);
        light = false;
        }
        
    }//GEN-LAST:event_jLabel1MousePressed
   
    public void arithmetic_operation(){
        switch(calculation){
            case 1: // Addition 
                ans = Double.parseDouble(
                        df.format(
                        num + Double.parseDouble(
                                text.getText())));
                text.setText(Double.toString(ans));
                break;
                
            case 2: // Substraction
                ans = Double.parseDouble(
                        df.format(
                        num - Double.parseDouble(
                                text.getText())));
                 
                text.setText(Double.toString(ans));
                break;
            case 3: // Multiplication
                ans = Double.parseDouble(
                        df.format(
                        num * Double.parseDouble(
                                text.getText())));
                text.setText(Double.toString(ans));
                break;
            case 4: // Division
                ans = Double.parseDouble(
                        df.format(
                        num / Double.parseDouble(
                                text.getText())));
                text.setText(Double.toString(ans));
                break;    
        }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton badd;
    private javax.swing.JButton bd;
    private javax.swing.JButton bdiv;
    private javax.swing.JButton bequal;
    private javax.swing.JButton bminus;
    private javax.swing.JButton bmult;
    private javax.swing.JButton breset;
    private javax.swing.JLabel cache;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField text;
    // End of variables declaration//GEN-END:variables
}
